<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Monthly Report — {{ $group->name }} — {{ $month->format('F Y') }}</title>
    <style>
        @page { margin: 10mm 8mm; }
        * { box-sizing: border-box; }
        body { font-family: DejaVu Sans, Arial, sans-serif; color:#1f2d3d; font-size: 8.5px; margin:0; }
        h1 { font-size: 15px; margin: 0 0 2px; }
        .meta { color:#697b8c; font-size: 9.5px; margin-bottom: 6px; }
        table { width:100%; border-collapse: collapse; }
        th, td { border:1px solid #b9c1c9; padding: 3px 4px; vertical-align: middle; }
        thead th { background:#e8eef5; font-size: 8px; text-align:center; }
        thead th.last { background:#dde9f4; }
        thead th.now  { background:#fff4cf; }
        td.num { text-align:right; }
        td.num.now { background:#fffbe6; }
        td.muted { color:#9aa5b3; }
        td.debt { color:#b32d2d; font-weight:bold; }
        tfoot td { background:#fff2cc; font-weight:bold; color:#b32d2d; text-align:right; }
        tfoot td.label { color:#1f2d3d; text-align:left; }

        .summary { margin-top: 10px; width: 55%; }
        .summary th { background:#f4f6f8; text-align:left; }
        .summary td { text-align:right; font-weight:bold; }
        .summary tr.total th, .summary tr.total td { background:#fff2cc; font-size: 11px; }

        .footer { margin-top: 10px; color:#697b8c; font-size: 8.5px; text-align:right; }
        .header { display: table; width: 100%; margin-bottom: 6px; }
        .header .left, .header .right { display: table-cell; vertical-align: middle; }
        .header .right { text-align: right; font-size: 9.5px; color:#697b8c; }
    </style>
</head>
<body>

@php
    $cur = fn ($n) => $n == 0 ? '' : number_format((float) $n, 0);
    $sheet = $report['sheet'];
    $rows  = $sheet['rows'];
    $t     = $sheet['totals'];
    $sum   = $sheet['summary'];
    $monthLabel = $report['header']['month']->format('m/Y');
@endphp

<div class="header">
    <div class="left">
        <h1>{{ $group->name }} — Raporo y'Ukwezi</h1>
        <div class="meta">{{ $report['header']['month_label'] }} ({{ $monthLabel }})</div>
    </div>
    <div class="right">
        Generated by {{ $report['header']['generated_by'] }}<br>
        on {{ $report['header']['generated_at']->toDayDateTimeString() }}
    </div>
</div>

<table>
    <thead>
        <tr>
            <th rowspan="2" style="width:50px">Ukwezi<br>{{ $monthLabel }}</th>
            <th rowspan="2" style="width:24px">No</th>
            <th rowspan="2" style="text-align:left; width:130px">Amazina</th>
            <th colspan="5" class="last">Ukwezi Gushize</th>
            <th colspan="7" class="now">Uku Kwezi</th>
            <th rowspan="2" class="now">Umwenda</th>
        </tr>
        <tr>
            <th class="last">Ibirarane arimo</th>
            <th class="last">Ibirarane byishywe</th>
            <th class="last">Inyungu y'inyungu kubukererwe</th>
            <th class="last">Inyungu y'inyungu kunguzanyo</th>
            <th class="last">Ubukererwe bwishyu</th>

            <th class="now">Ayinjiye</th>
            <th class="now">Inyungu n'ubukererwe</th>
            <th class="now">Inguzanyo asanganywe</th>
            <th class="now">Inguzanyo nshya itanzwe</th>
            <th class="now">Inyungu kunguzanyo</th>
            <th class="now">Inguzanyo yishyuwe</th>
            <th class="now">Inyungu yishyuwe</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($rows as $i => $r)
            <tr>
                @if ($i === 0)
                    <td rowspan="{{ count($rows) }}" style="text-align:center; font-weight:bold; background:#f4f6f8">
                        Ukwezi<br>{{ $monthLabel }}
                    </td>
                @endif
                <td style="text-align:center">{{ $r['no'] }}</td>
                <td>{{ $r['member_name'] }}</td>
                <td class="num">{{ $cur($r['last_arrears_in']) }}</td>
                <td class="num">{{ $cur($r['last_arrears_paid']) }}</td>
                <td class="num">{{ $cur($r['last_late_interest']) }}</td>
                <td class="num">{{ $cur($r['last_loan_interest']) }}</td>
                <td class="num">{{ $cur($r['last_arrears_outstanding']) }}</td>
                <td class="num now">{{ $cur($r['now_money_in']) }}</td>
                <td class="num now">{{ $cur($r['now_late_interest_in']) }}</td>
                <td class="num now">{{ $cur($r['now_loan_existing']) }}</td>
                <td class="num now">{{ $cur($r['now_loan_new']) }}</td>
                <td class="num now">{{ $cur($r['now_loan_interest_charged']) }}</td>
                <td class="num now">{{ $cur($r['now_loan_principal_paid']) }}</td>
                <td class="num now">{{ $cur($r['now_loan_interest_paid']) }}</td>
                <td class="num debt">{{ $cur($r['debt_now']) }}</td>
            </tr>
        @endforeach
    </tbody>
    @if (count($rows))
        <tfoot>
            <tr>
                <td></td><td></td>
                <td class="label">Tatal</td>
                <td>{{ $cur($t['last_arrears_in']) }}</td>
                <td>{{ $cur($t['last_arrears_paid']) }}</td>
                <td>{{ $cur($t['last_late_interest']) }}</td>
                <td>{{ $cur($t['last_loan_interest']) }}</td>
                <td>{{ $cur($t['last_arrears_outstanding']) }}</td>
                <td>{{ $cur($t['now_money_in']) }}</td>
                <td>{{ $cur($t['now_late_interest_in']) }}</td>
                <td>{{ $cur($t['now_loan_existing']) }}</td>
                <td>{{ $cur($t['now_loan_new']) }}</td>
                <td>{{ $cur($t['now_loan_interest_charged']) }}</td>
                <td>{{ $cur($t['now_loan_principal_paid']) }}</td>
                <td>{{ $cur($t['now_loan_interest_paid']) }}</td>
                <td>{{ $cur($sum['umutungo_wose']) }}</td>
            </tr>
        </tfoot>
    @endif
</table>

<table class="summary">
    <tr><th>Amafaranga yinjiye</th><td>{{ number_format($sum['amafaranga_yinjiye'], 0) }}</td></tr>
    <tr><th>Amafaranga ari kuri konti</th><td>{{ number_format($sum['amafaranga_ari_kuti_konti'], 0) }}</td></tr>
    <tr><th>Ayasohotse</th><td>{{ number_format($sum['ayasohotse'], 0) }}</td></tr>
    <tr><th>Asigaye kuri konti</th><td>{{ number_format($sum['asigaye_kuri_konti'], 0) }}</td></tr>
    <tr class="total"><th>Umutungo wose</th><td>{{ number_format($sum['umutungo_wose'], 0) }} {{ $report['header']['currency'] }}</td></tr>
</table>

<div class="footer">
    Generated by {{ $report['header']['generated_by'] }} on {{ $report['header']['generated_at']->toDayDateTimeString() }}
</div>

</body>
</html>
