<?php

namespace App\Providers;

use App\Models\ContributionPaymentRequest;
use App\Models\Group;
use App\Policies\ContributionPaymentRequestPolicy;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\View;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function register(): void {}

    public function boot(): void
    {
        Gate::policy(ContributionPaymentRequest::class, ContributionPaymentRequestPolicy::class);

        Paginator::useBootstrapFive();

        // ──────────────────────────────────────────────────────────────────
        // Track the live Replit workspace domain.
        //
        // Replit can rotate the workspace's public URL between sessions, but
        // APP_URL/ASSET_URL in `.replit` are static. When they go stale, every
        // absolute URL generated by url()/asset() (including stored avatars at
        // /storage/...) points to a dead host and the browser shows broken
        // images. To stay in sync we override config + URL root from
        // REPLIT_DEV_DOMAIN whenever it is present.
        // ──────────────────────────────────────────────────────────────────
        $replitDomain = env('REPLIT_DEV_DOMAIN');
        if ($replitDomain) {
            $replitUrl = 'https://'.$replitDomain;
            config([
                'app.url'       => $replitUrl,
                'app.asset_url' => $replitUrl,
            ]);
            URL::forceRootUrl($replitUrl);
        }

        // Force HTTPS only when the request actually arrived over HTTPS
        // (detected via X-Forwarded-Proto from the Replit proxy) or in
        // production. Do NOT force HTTPS based on app.url alone — the
        // Replit dev domain sets app.url to https:// but the preview pane
        // accesses the PHP server over plain HTTP internally, and a forced
        // HTTPS redirect would send it to the external domain causing a
        // blank/hanging preview.
        $request = request();
        $isHttps = $request && (
            $request->isSecure()
            || strtolower((string) $request->header('x-forwarded-proto')) === 'https'
        );

        if (app()->environment('production') || $isHttps) {
            URL::forceScheme('https');
        }

        // Make the active-group context available to every authenticated view.
        View::composer('*', function ($view) {
            if (! Auth::check()) return;

            $user       = Auth::user();
            $accessible = $user->accessibleGroups();
            $activeId   = session('active_group_id');
            $active     = $activeId ? $accessible->firstWhere('id', $activeId) : null;

            $view->with('activeGroup',      $active);
            $view->with('accessibleGroups', $accessible);
        });

        // Notification bell (unread count + recent activities).
        View::composer(
            ['partials.topbar', 'layouts.app'],
            \App\View\Composers\NotificationsComposer::class
        );

        // Provinces list for any view that includes the cascading-location partial.
        View::composer('partials.location_cascade', function ($view) {
            $view->with('provinces', \App\Models\Province::orderBy('name')->get(['code', 'name']));
        });
    }
}
